config/routes.rb
Rails.application.routes.draw do

  resources :users, only: [:new, :create]
  resources :sessions, only: [:new, :create, :destroy]

  resources :movies

  root 'static#home'
  get '/about' => 'static#about'
  get '/cat-pictures(/:number_of_cats)' => 'static#cats', as: :cat_pictures

  get '/sign-in' => 'sessions#new'
  delete '/sign-out' => 'sessions#destroy'

  get '/sign-up' => 'users#new'
  post '/users' => 'users#create'

  get '/add_favorite' => 'movies#favorite_movie'
  delete '/delete_favorite' => 'movies#destroy_favorite'

end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
  belongs_to :user
  belongs_to :movie
  validates_uniqueness_of :movie_id, scope: :user_id
end

app/models/movie.rb
class Movie < ActiveRecord::Base
  has_many :favorites
  has_many :users, through: :favorites
  validates_presence_of :title, :rating
  validates :title, :format => { :with => /\A[a-zA-Z\d\s\W]*\z/,
    message: "only allows letters and numbers" }
  validates :rating, :inclusion => {:in => 0..10, :message => "must be between 0 and 10"}
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :favorites
  has_many :movies, through: :favorites
  has_secure_password
  validates_uniqueness_of :email
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
private

  def current_user
    User.find_by(id: session[:user_id])
  end
  helper_method :current_user

  def user_signed_in?
    !!current_user
  end
  helper_method :user_signed_in?

def only_allow_signed_in_users
  unless user_signed_in?
    redirect_to sign_in_url, notice: 'You must sign in to access this part of the app.'
  end
end

end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :set_movie, only: [:show, :edit, :update, :destroy]
  before_action :only_allow_signed_in_users, except: [:index, :show]

  # GET /movies
  # GET /movies.json
  def index
    @movies = Movie.all.paginate(page: params[:page], per_page: 5)
    @fav_mov = current_user.movies
  end

  # GET /movies/1
  # GET /movies/1.json
  def show
    @users = @movie.users
  end

  # GET /movies/new
  def new
    @movie = Movie.new
  end

  # GET /movies/1/edit
  def edit
  end

  # POST /movies
  # POST /movies.json
  def create
    @movie = Movie.new(movie_params)

    respond_to do |format|
      if @movie.save
        format.html { redirect_to @movie, notice: 'Movie was successfully created.' }
        format.json { render :show, status: :created, location: @movie }
      else
        format.html { render :new }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /movies/1
  # PATCH/PUT /movies/1.json
  def update
    respond_to do |format|
      if @movie.update(movie_params)
        format.html { redirect_to @movie, notice: 'Movie was successfully updated.' }
        format.json { render :show, status: :ok, location: @movie }
      else
        format.html { render :edit }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movies/1
  # DELETE /movies/1.json
  def destroy
    @movie.destroy
    respond_to do |format|
      format.html { redirect_to movies_url, notice: 'Movie was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def favorite_movie
    @favorite = Favorite.new(user_id: current_user.id, movie_id: params[:movie_id])

      if @favorite.save
        redirect_to '/movies', notice: 'Favorite was successfully added.'
      else
        redirect_to '/movies', notice: 'Movie is already Favorite'
      end
    end

  def destroy_favorite
    @favorite = Favorite.find_by(user_id: current_user.id, movie_id: params[:movie_id])
    @favorite.destroy
    respond_to do |format|
      format.html { redirect_to movies_url, notice: 'Favorite was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_movie
      @movie = Movie.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def movie_params
      params.require(:movie).permit(:title, :rating, :release_date)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_url, notice: 'Logged In!'
    else
      flash.alert = 'Invalid email/password combination. Please try again.'
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: 'Successfully signed out!'
  end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def home
  end

  def about
  end

  def cats
    @cats = CatAPI.new.get_images(results_per_page: params[:number_of_cats] || 1)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
  end

  def create
    user = User.new(user_params)
    if user.save
      session[:user_id] = user.id
      redirect_to '/'
    else
      redirect_to '/sign-up', notice: 'Email already exists, please use different email'
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_helper.rb
module StaticHelper
  def current_time_and_date
    Time.now.strftime('%B %-d, %Y at %-l:%M%P')
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MyNewApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <ul>
    <li><h1><%= link_to 'Home', root_path %></h1></li>
    <li><h1><%= link_to 'About', about_path %></h1></li>
    <li><h1><%= link_to 'Cat Pictures', cat_pictures_path %></h1></li>
    <li><h1><%= link_to 'Movies', movies_path %></h1></li>
  </ul>
  <%= yield %>

  <% flash.each do |type, message| %>
  <div class="<%= type %>">
    <p><%= message %></p>
  </div>
  <% end %>

  <% if user_signed_in? %>
  <li>Signed in as <%= current_user.email  %></li>
  <li><%= link_to "Sign Out", sign_out_path, method: :delete %></li>
  <% else %>
  <li><%= link_to "Sign In", sign_in_path %></li>
  <li><%= link_to "Sign Up", sign_up_path %></li>
  <% end %>
</body>
</html>

app/views/movies/_form.html.erb
<%= form_for(@movie) do |f| %>
  <% if @movie.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@movie.errors.count, "error") %> prohibited this movie from being saved:</h2>

      <ul>
      <% @movie.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :rating %><br>
    <%= f.text_field :rating %>
  </div>
  <div class="field">
    <%= f.label :release_date %><br>
    <%= f.date_select :release_date, :start_year => 1878 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/movies/edit.html.erb
<h1>Editing movie</h1>

<%= render 'form' %>

<%= link_to 'Show', @movie %> |
<%= link_to 'Back', movies_path %>

app/views/movies/index.html.erb
<h1>Listing movies</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Rating</th>
      <th>Release date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @movies.each do |movie| %>
    <tr>
      <td><%= movie.title %></td>
      <td><%= movie.rating %></td>
      <td><%= movie.release_date %></td>
      <td><%= link_to 'Show', movie %></td>
      <% if user_signed_in? %>
      <td><%= link_to 'Edit', edit_movie_path(movie) %></td>
      <td><%= link_to 'Destroy', movie, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <td><%= link_to 'Favorite', add_favorite_path(movie_id: movie.id) %></td>
      <% end %>
    </tr>
    <% end %>
  </tbody>
</table>
<%= will_paginate @movies %>

<br>
<% if user_signed_in? %>
<%= link_to 'New Movie', new_movie_path %>
<% end %>

<br>

<h1>Favorites</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Rating</th>
      <th>Release date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @fav_mov.each do |fav| %>
    <tr>
      <td><%= fav.title %></td>
      <td><%= fav.rating %></td>
      <td><%= fav.release_date %></td>
      <td><%= link_to 'Show', fav %></td>
      <td><%= link_to 'Destroy', delete_favorite_path(movie_id: fav.id), method: :delete, data: { confirm: 'Are you sure?' }%></td>
    </tr>
    <% end %>
  </tbody>
</table>

<br><br>

app/views/movies/new.html.erb
<h1>New movie</h1>

<%= render 'form' %>

<%= link_to 'Back', movies_path %>

app/views/movies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @movie.title %>
</p>

<p>
  <strong>Rating:</strong>
  <%= @movie.rating %>
</p>

<p>
  <strong>Release date:</strong>
  <%= @movie.release_date %>
</p>

<h1>Favorited By</h1>
<ul>
  <% @users.each do |user| %>
    <li><%= user.email %></li>
  <% end %>
  <end>
</ul>

<% if user_signed_in? %>
  <%= link_to 'Edit', edit_movie_path(@movie) %> |
  <%= link_to 'Back', movies_path %>
<% else %>
  <%= link_to 'Back', movies_path %>
<% end %>

app/views/users/new.html.erb
<%= form_for :user, url: '/users' do |f| %>

  Email: <%= f.text_field :email %>
  Password: <%= f.password_field :password %>
  Password Confirmation: <%= f.password_field :password_confirmation %>
  <%= f.submit "Submit" %>

<% end %>